// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5vZM5wdwgCnnn9lsL9kMJIKXIMqiUpk',
    appId: '1:932850866606:web:c141dbbb71a3616606103f',
    messagingSenderId: '932850866606',
    projectId: 'safe-5adff',
    authDomain: 'safe-5adff.firebaseapp.com',
    storageBucket: 'safe-5adff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIXA7oz9aMXPpOxcGpC3-gFUo2nUX1RUI',
    appId: '1:932850866606:android:ef23f2f8a3f36c6b06103f',
    messagingSenderId: '932850866606',
    projectId: 'safe-5adff',
    storageBucket: 'safe-5adff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmeDfoociiSbviNFJXSlTRxzYKB14A6M',
    appId: '1:932850866606:ios:a65eee2df7a56f2a06103f',
    messagingSenderId: '932850866606',
    projectId: 'safe-5adff',
    storageBucket: 'safe-5adff.appspot.com',
    iosClientId: '932850866606-8hc3g5o46pog1i2ejq7411f5v31942j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.safefoodieLoginMerge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmeDfoociiSbviNFJXSlTRxzYKB14A6M',
    appId: '1:932850866606:ios:a65eee2df7a56f2a06103f',
    messagingSenderId: '932850866606',
    projectId: 'safe-5adff',
    storageBucket: 'safe-5adff.appspot.com',
    iosClientId: '932850866606-8hc3g5o46pog1i2ejq7411f5v31942j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.safefoodieLoginMerge',
  );
}
